version: 2

seeds:
  - name: productsubcategory
    config:
      database: adventureworks
      schema: production
      column_types:
        productsubcategoryid: integer
        productcategoryid: integer
        name: varchar
        modifieddate: timestamp
