adventureworks:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VNGKZGP.LV77681
      

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: dw
      warehouse: xsmall_wh
      schema: staging
      threads: 12
      client_session_keep_alive: False
