warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: vngkzgp-lv77681

      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: "ACCOUNTADMIN"
      database: "dw"
      warehouse: "XSMALL_WH"
      schema: "staging"
      threads: 12
      client_session_keep_alive: False
